### ISSUE TITLE
Hello sir

### ISSUE THREAD

**Issue by pskvortsov** [kna986/java_hw#1]
Hello. How are you? @kna986

**Comment by Legionivo** [comment]
Nicolay, we miss you!

**Comment by kna986** [comment]
Mas o menos, gracias. Y tu?

**Comment by pskvortsov** [comment]
@kna986 в семью вернуться не хочешь?

**Comment by kna986** [comment]
Я слишком эпично выпилился) Мгм да, чересчур даже.

**Comment by pskvortsov** [comment]
@kna986 мы скучаем, возвращайся давай

**Comment by pskvortsov** [comment]
@kna986 
![blabla](http://demotivation.me/images/20130128/yp4ujqrdx9nj.jpg)

**Comment by kna986** [comment]
Может позжей. Щас много проблем, в любом случае пассивный режим будет месяца два наверное.

**Comment by Legionivo** [comment]
@kna986  2 месяца истекает завтра
