### ISSUE TITLE
Уже прошло 2 месяца, го обратно

### ISSUE THREAD

**Issue by pskvortsov** [kna986/java_hw#3]
@kna986 ping

**Comment by kna986** [comment]
![index](https://user-images.githubusercontent.com/15412803/28637861-9ed4a0ea-724b-11e7-9a82-bce4b73e08d9.jpeg)

**Comment by gr3edo** [comment]
Николай Анатольевич, мы ждем ведь!

**Comment by artemnikitin** [comment]
Why ?!!

**Comment by kna986** [comment]
Чего это вдруг? Неспроста это что-то..
![1377283768_510071399](https://user-images.githubusercontent.com/15412803/28670464-71aff916-72e1-11e7-89ce-0acdbbf440e0.jpg)

**Comment by artemnikitin** [comment]
Да брось, соскучились просто :)

**Comment by pskvortsov** [comment]
@kna986 https://software-testers.herokuapp.com/

**Comment by kna986** [comment]
You recently requested a password reset for your account on SoftwareTesters, but it looks like your account was deactivated, so we can't reset your password. We're sorry about that!
